language: c

env:
  matrix:
    - python=3.6  CONDA_PY=36  CONDA_NPY=112

  global:
    -   secure: "YmuE3UEiCyFP5HBKu96pUlMn/QVS95DJU1g2+YZZZH02rG0y7JmNVT38c8KJlzeDVz4JC0WtkT79zsZlchVAbCHiKrEXf09LWEj7/Ny/4kcDB+I8cide1K/an4OngFe6rE4cbXkEDE2L06g++Ch6BQLxCVz87dX1GgTe+n8LtpCzQi12fyVVikKVHCmXbe4dQ3nQDnmTKW0tgwiH2uXbahC039uDi4UC3VqGaZB2IE8RTkuougL4JwYCnSfaClGG8WDgH6VUCe5P5DhNlm/ZjwdfwcH1UFtaT9ybHC5Xydi31mYIO15dttGmOFxNH9LTXSoYkGBeWdbMhi4J0j0rzOJilkccwD4fWpEeY0ATkOe9EXCJambccPLkfGv2a4EVzOFxYrgn8LrjCw+VoHtr+PF0+9S+Z2jAM65Oo05mx2f5Pl9rNmPYjkgmDR9uuMW6oUE6QMUsV3Lby41BicxtP8HBQrq+JTbJOviIm3ABaoOJLzK3vbpi3rN4tYXhbi8HOjAoalntzkYlRzn8Hou6NVvWdJfFhMAy1eJtK4Cz78c+6fGsAm/6QR8yVyYDuPvvfMQzLHmQmoMMr5eW/tRfuwPbP/ktZ/pMVv999ABxCpzv5udfFC/Ol5XpgjyxZSL2sTV7sRKfV8Y2y4dCwAeOZOKB8AvK1XR6RksxdhOzCAg="

install:
  - source continuous-integration/travis/install.sh

script:
  - conda build conda-recipe --quiet

# after_success:
#   - python continuous-integration/move-conda-package.py conda-recipe
#   - binstar -t $BINSTAR_TOKEN upload --force *.tar.bz2
